#title: CTP431 Final Project Music to Text to Music (m2t2m)
#description: >

  
  #Donghyeon Choi, Seunghyun Cho <br>
  #KAIST Graduate School of AI Semiconductor, 
  #KAIST School of Electrical Engineering
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman